### ISSUE TITLE
Is it possible to limit fps in the player

### ISSUE THREAD

**Issue by DiHubKi** [fraunhoferhhi/vvdecWebPlayer#1]
The videos are going too fast

**Comment by K-os** [comment]
Can you please give some information about what you are doing? Are you playing an MP4 file or a raw bitstream?

When plaing an MP4 file, the player uses the frame rate specified in the file. For raw bitstreams it uses the default frame rate of 50 Hz defined in shell.js `const DEFAULT_FPS = 50;`

**Comment by DiHubKi** [comment]
I'm not good at this so I used mp4 files but in the format .266 so I renamed them to .mp4 but now the player show downloading 100% and the video doesn't work.

**Comment by K-os** [comment]
If the files are named .266 they are probably not mp4 files, but raw bitstreams. Just don't rename them and change the DEFAULT_FPS in `shell.js` to the frame rate you want.

Renaming the file does not change it's format, only its name. You can package the bitstreams in mp4-files using MP4Box from the GPAC-Project: https://github.com/gpac/gpac.

**Comment by DiHubKi** [comment]
Thanks it worked using mp4box
