### ISSUE TITLE
Problems Building WASM 

### ISSUE THREAD

**Issue by asqarkababi** [fraunhoferhhi/vvdecWebPlayer#2]
I installed emscripten with Chocolatey and CMake and added both to the PATH but when trying to build i get the following error message am i doing something wrong 
<img width="638" alt="Screenshot 2022-02-22 091415" src="https://user-images.githubusercontent.com/96051597/155090658-8bebb368-530d-4f6f-b460-fd96d881e58b.png">
the PATH is like follows: 
<img width="374" alt="Screenshot 2022-02-22 091453" src="https://user-images.githubusercontent.com/96051597/155090724-ca56bedd-8435-4738-b771-2177e3c5828a.png">
<img width="374" alt="Screenshot 2022-02-22 091617" src="https://user-images.githubusercontent.com/96051597/155090730-fe52d227-6185-4930-8e2c-58f07950cd47.png">
Thanks in Advance

**Comment by K-os** [comment]
Looks like you didn't activate your Emscripten environment. There is a script `emsdk_env.bat` in the emsdk directory, that you need to run first. It sets the environment variables for your Emscripten install. (see here: https://emscripten.org/docs/getting_started/downloads.html#installation-instructions-using-the-emsdk-recommended)

Also, why do you have this `emsdk\bazel` subdirectory in your PATH? I've never seen that mentioned anywhere in the Emscripten documentation.

**Comment by asqarkababi** [comment]
> Looks like you didn't activate your Emscripten environment. There is a script `emsdk_env.bat` in the emsdk directory, that you need to run first. It sets the environment variables for your Emscripten install. (see here: https://emscripten.org/docs/getting_started/downloads.html#installation-instructions-using-the-emsdk-recommended)
> 
> Also, why do you have this `emsdk\bazel` subdirectory in your PATH? I've never seen that mentioned anywhere in the Emscripten documentation.

Thank you for your answer when i try to access the cmake on visual studio throught windows i get this error 
<img width="185" alt="Screenshot 2022-02-22 122452" src="https://user-images.githubusercontent.com/96051597/155123267-31317f9a-1829-47ab-8d67-12f24bf02092.png">
I didnt know where the emsdk folder is

**Comment by K-os** [comment]
> Thank you for your answer when i try to access the cmake on visual studio throught windows i get this error <img alt="Screenshot 2022-02-22 122452" width="185" src="https://user-images.githubusercontent.com/96051597/155123267-31317f9a-1829-47ab-8d67-12f24bf02092.png">

How am I supposed to get any information out of that screenshot?

I don't know how Emscripten integrates with Visual Studio, but if you don't want to actually work on the code, you don't need it. The easiest is building from the command line using the two commands from the readme file:
```
emcmake cmake -B build/wasm
cmake --build build/wasm
```

> I didnt know where the emsdk folder is

If you don't know where you installed emsdk, I can't help you, but guessing from your first screenshot you put it under `C:\Users\mmard\emsdk`.

Please read and follow the [Emscripten installation documentation](https://emscripten.org/docs/getting_started/downloads.html). When your Power Shell finds both commands `cmake` and `emcmake`, and you still have problems compiling, please come back to me. Until then, you have to figure out yourself where you installed stuff.

**Comment by asqarkababi** [comment]
<img width="394" alt="Screenshot 2022-02-22 170209" src="https://user-images.githubusercontent.com/96051597/155179822-df3f293a-069d-494b-b035-14f5412f9d3b.png">
CMake Works but emcmake not some commands like activate latest dont work aswell i frustrated i dont know what to do could you give me a hint please ?

**Comment by asqarkababi** [comment]
> > Thank you for your answer when i try to access the cmake on visual studio throught windows i get this error <img alt="Screenshot 2022-02-22 122452" width="185" src="https://user-images.githubusercontent.com/96051597/155123267-31317f9a-1829-47ab-8d67-12f24bf02092.png">
> 
> How am I supposed to get any information out of that screenshot?
> 
> I don't know how Emscripten integrates with Visual Studio, but if you don't want to actually work on the code, you don't need it. The easiest is building from the command line using the two commands from the readme file:
> 
> ```
> emcmake cmake -B build/wasm
> cmake --build build/wasm
> ```
> 
> > I didnt know where the emsdk folder is
> 
> If you don't know where you installed emsdk, I can't help you, but guessing from your first screenshot you put it under `C:\Users\mmard\emsdk`.
> 
> Please read and follow the [Emscripten installation documentation](https://emscripten.org/docs/getting_started/downloads.html). When your Power Shell finds both commands `cmake` and `emcmake`, and you still have problems compiling, please come back to me. Until then, you have to figure out yourself where you installed stuff.

Thank you very much i will try it out

**Comment by asqarkababi** [comment]
So i installed all of the requierements correctly i have this problem to open the localhost
<img width="953" alt="Screenshot 2022-02-22 213603" src="https://user-images.githubusercontent.com/96051597/155216346-5a52f663-9da6-452c-ac6f-9c69127b1cb2.png">
<img width="668" alt="Screenshot 2022-02-22 213843" src="https://user-images.githubusercontent.com/96051597/155216351-a135c296-0023-442f-9976-8e584c2151e0.png">

**Comment by asqarkababi** [comment]
I get this error 
<img width="960" alt="Screenshot 2022-02-23 080700" src="https://user-images.githubusercontent.com/96051597/155274797-a795386a-cc80-411d-a18c-6316209dacef.png">
Could you give me a hint please

**Comment by K-os** [comment]
Hmm, Interesting. It should work in Chrome. Is your browser up to date?

What are you using as a Webserver? The provided script? Did you change anything in the script?

Can you please look into the development console in the browser (F12 -> Console) if there are any errors reported?

**Comment by asqarkababi** [comment]
> Hmm, Interesting. It should work in Chrome. Is your browser up to date?
> 
> What are you using as a Webserver? The provided script? Did you change anything in the script?
> 
> Can you please look into the development console in the browser (F12 -> Console) if there are any errors reported?

My Chrome is the latest Version(Version 98.0.4758.102 (Offizieller Build) (64-Bit)) and uptodate i use the Webserver for Chrome as im used to it through my studies its using http://127.0.0.1:8887/ as LocalHost address
I didnt change the script only tried to add my Video data in the Bitstream.json

**Comment by asqarkababi** [comment]
Maybe it has to do with this error : 
<img width="884" alt="Screenshot 2022-02-23 182828" src="https://user-images.githubusercontent.com/96051597/155373868-fa5606d3-6a87-4e4b-aff9-e9d1128305bb.png">

I think i have to implement a server.py for it to work if im correct

**Comment by adamjw24** [comment]
> I didnt change the script only tried to add my Video data in the Bitstream.json

And yet I see that your screenshot differs from: https://github.com/fraunhoferhhi/vvdecWebPlayer/blob/master/wasm_test-server.py

![image](https://user-images.githubusercontent.com/70575289/155482063-62ae112c-aff1-4c03-ac45-dc67a702942b.png)

Please be careful with what you do and try to make it easier for us.

**Comment by asqarkababi** [comment]
> > I didnt change the script only tried to add my Video data in the Bitstream.json
> 
> And yet I see that your screenshot differs from: https://github.com/fraunhoferhhi/vvdecWebPlayer/blob/master/wasm_test-server.py
> 
> ![image](https://user-images.githubusercontent.com/70575289/155482063-62ae112c-aff1-4c03-ac45-dc67a702942b.png)
> 
> Please be careful with what you do and try to make it easier for us.

Of course i think i downloaded an older version of the Program on github im now checking if the codes are identical

**Comment by adamjw24** [comment]
No, you changed it. And you either forgot or you're trolling us, really can't tell.

You can use `git status` to check what you did.

**Comment by asqarkababi** [comment]
> No, you changed it. And you either forgot or you're trolling us, really can't tell.
> 
> You can use `git status` to check what you did.

I downloaded this version: https://github.com/1div0/vvdecWebPlayer also not your original one and im new to github and have to get used to it

**Comment by adamjw24** [comment]
Why don't you analyze their changes and evaluate if they apply to you? You could also ask them. This is not our code.

If you want our help, the least you could do is actually use our code.

**Comment by asqarkababi** [comment]
> Why don't you analyze their changes and evaluate if they apply to you? You could also ask them. This is not our code.
> 
> If you want our help, the least you could do is actually use our code.

Im very Sorry im a bit mixed out and apologize for my error i thought i cloned the original one

**Comment by adamjw24** [comment]
Good. Does it work now?

**Comment by asqarkababi** [comment]
> Good. Does it work now?


Thank you for your understanding and im very grateful for your time and help So i downloaded the original one from yours it but i get
<img width="779" alt="Screenshot 2022-02-24 100114" src="https://user-images.githubusercontent.com/96051597/155492639-dc411b36-5927-4df1-9d7b-12ca9b78f3b4.png">
<img width="674" alt="Screenshot 2022-02-24 100252" src="https://user-images.githubusercontent.com/96051597/155492641-e173e410-c7ea-4635-b69f-b1868ca5b740.png">
 after i use the wasm_test-server following error messages the eventhandler dont work for me

**Comment by adamjw24** [comment]
Strange, didn't see that one yet. Maybe have a look at https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled

**Comment by asqarkababi** [comment]
> Strange, didn't see that one yet. Maybe have a look at https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled

Still the same issue even after activating WEBGL HW Acceleration 
<img width="556" alt="Screenshot 2022-02-24 104800" src="https://user-images.githubusercontent.com/96051597/155500371-9d1f72d1-fb26-4a30-af53-20d4c02121c1.png">
<img width="583" alt="Screenshot 2022-02-24 104829" src="https://user-images.githubusercontent.com/96051597/155500416-ef8a5a63-ef9e-4f1d-a4b0-f17677a53568.png">

**Comment by adamjw24** [comment]
And other browsers? Edge/Firefox?

**Comment by K-os** [comment]
Where do these electron error messages come from? Those messages in your terminal don't look like they are coming from the wasm_test-server.py script.

Could you please try a different Browser? Firefox for example?

**Comment by K-os** [comment]
Oh, I was too slow.

**Comment by asqarkababi** [comment]
> And other browsers? Edge/Firefox?

On Edge its the same with the error message like on chrome i will try it again 
For the server it connects but i get following error 
<img width="960" alt="Screenshot 2022-02-24 110040" src="https://user-images.githubusercontent.com/96051597/155502380-62def9da-d122-451d-9cf4-ef7c4b41cf49.png">

**Comment by K-os** [comment]
There is something really weird going on with the requests your browser is sending.

**Comment by asqarkababi** [comment]
> There is something really weird going on with the requests your browser is sending.

And now after i run the .py File over visual Studio it looks like this : 
<img width="956" alt="Screenshot 2022-02-24 110947" src="https://user-images.githubusercontent.com/96051597/155503867-bf9fcc1b-ef97-4cdc-ae2c-3f26faeb8488.png">
Its very strange

**Comment by K-os** [comment]
:

**Comment by K-os** [comment]
If you give me an email address, I can provide you a link to our demo-site. There you can try if it works in your browser.

**Comment by asqarkababi** [comment]
> If you give me an email address, I can provide you a link to our demo-site. There you can try if it works in your browser.

This is my email address: \<private mail address removed\>
Right now when im trying to run .py on visual Studio i get the following error code: 
<img width="688" alt="Screenshot 2022-02-24 115049" src="https://user-images.githubusercontent.com/96051597/155510507-21915f0a-1299-4f10-a28b-34334e007ee6.png">
Im so confused now

**Comment by adamjw24** [comment]
There might be thousand reasons for this, and its also not easy diagnosing this without physical access to your computer. It could be your firewall, some funny security settings on your computer (is it a work/school computer? maybe some strict organization rules). Considering this error, I would say you should try running this as administrator (just start visual studio as administrator). But of course, as a random person from the internet asking you to run our code with elevated privilege, you have to know for yourself if you want to risk it. So be warned.

**Comment by asqarkababi** [comment]
> There might be thousand reasons for this, and its also not easy diagnosing this without physical access to your computer. It could be your firewall, some funny security settings on your computer (is it a work/school computer? maybe some strict organization rules). Considering this error, I would say you should try running this as administrator (just start visual studio as administrator). But of course, as a random person from the internet asking you to run our code with elevated privilege, you have to know for yourself if you want to risk it. So be warned.

Im careful i only need it for a presentation  I disabled my firewall and run it as  an administrator and its connecting now with the server and i dont get errors anymore and my computer is a private one neither from university nor any other institution no fear 
<img width="667" alt="Screenshot 2022-02-24 120444" src="https://user-images.githubusercontent.com/96051597/155512729-e37c8210-124f-44d1-8147-1b545832a9c6.png">

There is only one problem left and that is why the play and stop buttons dont work even the eventhandlers are defined in the shell.js i will try to figure this out

**Comment by adamjw24** [comment]
For me, the buttons sometimes need a while to active (up to 5s).

I think @K-os is more suited to help you from here, and he's busy with other stuff for the rest of the day.

Just a few questions to make sure everything is set up correctly:
* you also have vvdecapp.wasm and vvdecapp.worker.js in the bin directory? (your log doesn't show them being downloaded, does the inspector console say anything)?
* your bitstreams.json actually contains proper bitstreams (does the download button next to the drop-down list work)?

**Comment by asqarkababi** [comment]
> For me, the buttons sometimes need a while to active (up to 5s).
> 
> I think @K-os is more suited to help you from here, and he's busy with other stuff for the rest of the day.
> 
> Just a few questions to make sure everything is set up correctly:
> 
> * you also have vvdecapp.wasm and vvdecapp.worker.js in the bin directory? (your log doesn't show them being downloaded, does the inspector console say anything)?
> * your bitstreams.json actually contains proper bitstreams (does the download button next to the drop-down list work)?


Thank you very much for your help im very grateful 
Yes i have all of them in the bin copied as the step by step said
![InkedScreenshot 2022-02-24 124453](https://user-images.githubusercontent.com/96051597/155518603-5dee39f3-ab1b-400e-ba81-ba9c8f4977c8.jpg)
The Download Button doesnt work aswell and i cant download the .266 file
The inspector console gives me following errors: 
<img width="418" alt="Screenshot 2022-02-24 125154" src="https://user-images.githubusercontent.com/96051597/155518972-69bf3a2c-6c7b-43be-b052-1f46f5cc88c8.png">

**Comment by K-os** [comment]
> The Download Button doesnt work aswell and i cant download the .266 file
> The inspector console gives me following errors:
> <img alt="Screenshot 2022-02-24 125154" width="418" src="https://user-images.githubusercontent.com/96051597/155518972-69bf3a2c-6c7b-43be-b052-1f46f5cc88c8.png">

I think we are seeing two problems here:
1. We don't provide bitstreams with the code. So you need to put a .266-bitstream on the webserver and edit the bitstreams.json file to include that bitstream.
2. The error looks like your webserver is serving the Javascript-files with the wrong mime-type: it should be `Content-Type: application/javascript` instead of `text/plain`.

**Comment by asqarkababi** [comment]
> > The Download Button doesnt work aswell and i cant download the .266 file
> > The inspector console gives me following errors:
> > <img alt="Screenshot 2022-02-24 125154" width="418" src="https://user-images.githubusercontent.com/96051597/155518972-69bf3a2c-6c7b-43be-b052-1f46f5cc88c8.png">
> 
> I think we are seeing two problems here:
> 
> 1. We don't provide bitstreams with the code. So you need to put a .266-bitstream on the webserver and edit the bitstreams.json file to include that bitstream.
> 2. The error looks like your webserver is serving the Javascript-files with the wrong mime-type: it should be `Content-Type: application/javascript` instead of `text/plain`.

I added a .266 File in the bitstreams.json file it shows of in the select section
<img width="425" alt="Screenshot 2022-02-24 173214" src="https://user-images.githubusercontent.com/96051597/155566672-976cd02f-750c-4d87-a858-a0023b2fd3a1.png">
<img width="389" alt="Screenshot 2022-02-24 172933" src="https://user-images.githubusercontent.com/96051597/155566730-265390d0-fada-4a09-bf59-09719d7dcbfe.png">

<img width="404" alt="Screenshot 2022-02-24 172906" src="https://user-images.githubusercontent.com/96051597/155566768-7886646a-e420-48dd-b1e0-10713238524d.png">

I added the two bootstraps and now i only have the red ones even i changed mime in the iis option
<img width="840" alt="Screenshot 2022-02-24 201748" src="https://user-images.githubusercontent.com/96051597/155592188-4e73df23-c00f-4608-929b-00773b4d121d.png">

**Comment by K-os** [comment]
The .map files don't matter. You don't need those.

I updated the `wasm_test-server.py` to explicitly specify the mime-types for all used files. I don't know why that was a problem on your machine, this should hopefully fix it.

**Comment by asqarkababi** [comment]
> The .map files don't matter. You don't need those.
> 
> I updated the `wasm_test-server.py` to explicitly specify the mime-types for all used files. I don't know why that was a problem on your machine, this should hopefully fix it.

Thank you very much 
I tried to check it out but get this error is there a way to bypass this problem this error happen every other one when i start to debug on chrome
<img width="943" alt="Screenshot 2022-02-25 072805" src="https://user-images.githubusercontent.com/96051597/155666077-424610c2-a317-4851-807c-9d589a580517.png">
On Opera its working but i get following error do i have to insert a video in a folder that it gets recognized ?
<img width="908" alt="Screenshot 2022-02-25 074057" src="https://user-images.githubusercontent.com/96051597/155667413-1f2ccbbf-24e1-4f77-85cf-7e94f23d8a54.png">
<img width="719" alt="Screenshot 2022-02-25 074320" src="https://user-images.githubusercontent.com/96051597/155667559-01a85ba4-7896-47cb-a4b4-23d808ae8263.png">

**Comment by K-os** [comment]
> I tried to check it out but get this error is there a way to bypass this problem this error happen every other one when i start to debug on chrome

You mistyped the URL. There should be a colon `:` before the prot number 8000.


> On Opera its working but i get following error do i have to insert a video in a folder that it gets recognized ?

No, it just needs to be in the same directory. Make sure, that the name in the `bitstreams.json` exactly matches the actual file name (including capitalization).

**Comment by asqarkababi** [comment]
> > I tried to check it out but get this error is there a way to bypass this problem this error happen every other one when i start to debug on chrome
> 
> You mistyped the URL. There should be a colon `:` before the prot number 8000.
> 
> > On Opera its working but i get following error do i have to insert a video in a folder that it gets recognized ?
> 
> No, it just needs to be in the same directory. Make sure, that the name in the `bitstreams.json` exactly matches the actual file name (including capitalization).

Thank you very much its working flawlessly 
But one question as my video is lesser than 720p the output is pixelated has the video to be 1080p to have an flawless output ?
I get following error when i want to play a video file for both .266 and .mp4
<img width="679" alt="Screenshot 2022-02-25 103832" src="https://user-images.githubusercontent.com/96051597/155692101-1a3fb1f6-9b95-447e-930c-5ef43782d886.png">

**Comment by K-os** [comment]
> Thank you very much its working flawlessly
 
Oh, nice. Good to know.

> But one question as my video is lesser than 720p the output is pixelated has the video to be 1080p to have an flawless output ?

Hmm, that's weird. That shouldn't be the case. Any resolution should work fine. Can you upload the encoded video somewhere, so I can have a look at it?

> I get following error when i want to play a video file for both .266 and .mp4
> <img alt="Screenshot 2022-02-25 103832" width="679" src="https://user-images.githubusercontent.com/96051597/155692101-1a3fb1f6-9b95-447e-930c-5ef43782d886.png">

That is not an error. That's just some debugging output.

**Comment by asqarkababi** [comment]
> > Thank you very much its working flawlessly
> 
> Oh, nice. Good to know.
> 
> > But one question as my video is lesser than 720p the output is pixelated has the video to be 1080p to have an flawless output ?
> 
> Hmm, that's weird. That shouldn't be the case. Any resolution should work fine. Can you upload the encoded video somewhere, so I can have a look at it?
> 
> > I get following error when i want to play a video file for both .266 and .mp4
> > <img alt="Screenshot 2022-02-25 103832" width="679" src="https://user-images.githubusercontent.com/96051597/155692101-1a3fb1f6-9b95-447e-930c-5ef43782d886.png">
> 
> That is not an error. That's just some debugging output.

of course i could sent you a link on google drive if possible i will sent  the .mp4 file that doesnt play and the .266 too this is the link there are the mp4 files and .266 file that i told you [https://drive.google.com/drive/folders/1Y1gHSyFOwihY02WfP9G5DtdbImZeXvu8?usp=sharing](url)
And how much does it take to exit one videofile to start a new video from the selection ?

**Comment by K-os** [comment]
> And how much does it take to exit one videofile to start a new video from the selection ?

Sorry, I don't really understand you question. Do you mean you want to play multiple files back-to-back? That is already possible: in the "advanced" tab, there is a checkbox for "Loop over sequences". That should play all files in the selection menu and restart from the beginning.

**Comment by K-os** [comment]
> of course i could sent you a link on google drive if possible i will sent the .mp4 file that doesnt play and the .266 too this is the link there are the mp4 files and .266 file that i told you [https://drive.google.com/drive/folders/1Y1gHSyFOwihY02WfP9G5DtdbImZeXvu8?usp=sharing](url)

Ok, let's start with the raw bitstream. That is easiest to get started.

How did you produce the R.266 file. It looks like something went wrong in your encoding. Maybe you supplied the wrong resolution or wrong pixel-format to the encoder?

**Comment by K-os** [comment]
Ok, playing around with YUView I found out the actual resolution of the file you encoded. That seems to have been 540x360 pixels, but you encoded it at 1920x1080. That will not work. You have to tell the encoder the correct resolution of your input file.

Why are we still talking about that. @adamjw24 told you the same thing in the issue you opened in the vvdec repository: https://github.com/fraunhoferhhi/vvdec/issues/79#issuecomment-1047003074

**Comment by asqarkababi** [comment]
> > of course i could sent you a link on google drive if possible i will sent the .mp4 file that doesnt play and the .266 too this is the link there are the mp4 files and .266 file that i told you [https://drive.google.com/drive/folders/1Y1gHSyFOwihY02WfP9G5DtdbImZeXvu8?usp=sharing](url)
> 
> Ok, let's start with the raw bitstream. That is easiest to get started.
> 
> How did you produce the R.266 file. It looks like something went wrong in your encoding. Maybe you supplied the wrong resolution or wrong pixel-format to the encoder?

Yes thats the problem i made a mistake by writing -s 1920x1080 even the video is lower in resolution i made that before @adamjw24 told me the right way to encode i will correct and im now encode it to see if its working 

the mp4 files dont play and the yuv ones get aborted by the player is there any workaround to make the mp4s play ?

**Comment by asqarkababi** [comment]
Issue got solved thank you for your help
